# Generated by Django 4.2.4 on 2023-08-08 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_django', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default='Meu Blog', max_length=255),
        ),
    ]
